# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------


from .. import try_manual


# EXAMPLE: /LocalUsers/put/StorageAccountLocalUsers_Create
@try_manual
def step_account_local_user_create(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az storage account local-user create '
             '--account-name "sto2527" '
             '--permission-scopes permissions="rwdlc" resource-name="share1" service="file" '
             '--permission-scopes permissions="rl" resource-name="share2" service="file" '
             '--resource-group "{rg}" '
             '--username "user1"',
             checks=checks)


# EXAMPLE: /LocalUsers/put/StorageAccountLocalUsers_Update
@try_manual
def step_account_local_user_update(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az storage account local-user update '
             '--account-name "sto2527" '
             '--home-directory "dir1" '
             '--resource-group "{rg}" '
             '--username "user1"',
             checks=checks)


# EXAMPLE: /LocalUsers/get/StorageAccountGetLocalUser
@try_manual
def step_account_local_user_show(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az storage account local-user show '
             '--account-name "sto2527" '
             '--resource-group "{rg}" '
             '--username "user1"',
             checks=checks)


# EXAMPLE: /LocalUsers/get/StorageAccountListLocalUsers
@try_manual
def step_account_local_user_list(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az storage account local-user list '
             '--account-name "sto2527" '
             '--resource-group "{rg}"',
             checks=checks)


# EXAMPLE: /LocalUsers/post/StorageAccountListLocalUserKeys
@try_manual
def step_account_local_user_list_key(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az storage account local-user list-key '
             '--account-name "sto2527" '
             '--resource-group "{rg}" '
             '--username "user1"',
             checks=checks)


# EXAMPLE: /LocalUsers/delete/StorageAccountDeleteLocalUsers
@try_manual
def step_account_local_user_delete(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az storage account local-user delete -y '
             '--account-name "sto2527" '
             '--resource-group "{rg}" '
             '--username "user1"',
             checks=checks)

