# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

import os
from azure.cli.testsdk import ScenarioTest
from azure.cli.testsdk import ResourceGroupPreparer
from .example_steps import step_account_local_user_create
from .example_steps import step_account_local_user_show
from .example_steps import step_account_local_user_list
from .example_steps import step_account_local_user_list_key
from .example_steps import step_account_local_user_update
from .example_steps import step_account_local_user_delete
from .. import (
    try_manual,
    raise_if,
    calc_coverage
)


TEST_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), '..'))


# Env setup_scenario
@try_manual
def setup_scenario(test, rg):
    pass


# Env cleanup_scenario
@try_manual
def cleanup_scenario(test, rg):
    pass


# Testcase: Scenario
@try_manual
def call_scenario(test, rg):
    setup_scenario(test, rg)
    step_account_local_user_create(test, rg, checks=[])
    step_account_local_user_show(test, rg, checks=[])
    step_account_local_user_list(test, rg, checks=[])
    step_account_local_user_list_key(test, rg, checks=[])
    step_account_local_user_update(test, rg, checks=[])
    step_account_local_user_delete(test, rg, checks=[])
    cleanup_scenario(test, rg)


# Test class for Scenario
@try_manual
class StorageAccountLocalUserScenarioTest(ScenarioTest):

    @ResourceGroupPreparer(name_prefix='cliteststorage_res6977'[:7], key='rg', parameter_name='rg')
    def test_StorageAccountLocalUser_Scenario(self, rg):

        call_scenario(self, rg)
        calc_coverage(__file__)
        raise_if()

